# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - gripper_fingers_controller

  arm_controller:
    type: FollowJointTrajectory
    joints:
      - J1
      - J2
      - J3
      - J4
      - J5
      - J6
    action_ns: follow_joint_trajectory
  gripper_fingers_controller:
    type: GripperCommand
    joints:
      - Finger1
    action_ns: gripper_cmd
    default: true